using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Synaptrix.Generator;

/// <summary>
/// Emits closed pipeline-behavior registrations, one per (request, response) pair, for hosts that run
/// ahead-of-time compiled.
/// </summary>
/// <remarks>
/// An open-generic registration - <c>AddTransient(typeof(IPipelineBehavior&lt;,&gt;), typeof(Behavior&lt;,&gt;))</c> -
/// leaves the container to construct the closed type when someone asks for
/// <c>IPipelineBehavior&lt;SomeCommand, SomeResponse&gt;</c>. Generic code cannot be shared across value
/// types, so each such instantiation needs its own native code, and AOT only emits it for instantiations
/// it can see in the source. A response that is a struct - <c>ErrorOr&lt;T&gt;</c>, a tuple, an enum -
/// therefore fails at resolution time with "Unable to create a generic service for type ... because ...
/// is a ValueType". Writing every closed registration out as source puts those instantiations in front
/// of the compiler, so the native code exists.
/// </remarks>
internal static class AotPipelineBehaviorEmitter
{
    private const string PipelineBehaviorMetadataName = "Synaptrix.IPipelineBehavior`2";
    private const string StreamPipelineBehaviorMetadataName = "Synaptrix.IStreamPipelineBehavior`2";
    private const string RequestMetadataName = "Synaptrix.IRequest`1";
    private const string StreamRequestMetadataName = "Synaptrix.IStreamRequest`1";

    private static readonly SymbolDisplayFormat FullyQualified =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    /// <summary>
    /// Returns the generated source, or null when there is nothing to register.
    /// </summary>
    public static string? Generate(string generatedNamespace, Compilation compilation)
    {
        var behaviorInterface = compilation.GetTypeByMetadataName(PipelineBehaviorMetadataName);
        var streamBehaviorInterface = compilation.GetTypeByMetadataName(StreamPipelineBehaviorMetadataName);
        var requestInterface = compilation.GetTypeByMetadataName(RequestMetadataName);
        var streamRequestInterface = compilation.GetTypeByMetadataName(StreamRequestMetadataName);

        if (behaviorInterface is null && streamBehaviorInterface is null)
        {
            return null;
        }

        var types = VisibleTypes(compilation).ToList();

        var behaviors = types.Where(t => IsOpenGenericBehavior(t, behaviorInterface))
            .Select(WithoutTypeParameters)
            .OrderBy(name => name, System.StringComparer.Ordinal)
            .ToList();

        var streamBehaviors = types.Where(t => IsOpenGenericBehavior(t, streamBehaviorInterface))
            .Select(WithoutTypeParameters)
            .OrderBy(name => name, System.StringComparer.Ordinal)
            .ToList();

        var requests = ClosedRequests(types, requestInterface);
        var streamRequests = ClosedRequests(types, streamRequestInterface);

        var pairs = Pairs(behaviors, requests, "global::Synaptrix.IPipelineBehavior")
            .Concat(Pairs(streamBehaviors, streamRequests, "global::Synaptrix.IStreamPipelineBehavior"))
            .ToList();

        if (pairs.Count == 0)
        {
            return null;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// This file is automatically generated by Synaptrix.Generator.");
        sb.AppendLine("// Do not modify this file manually.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Synaptrix;");
        sb.AppendLine();
        sb.AppendLine($"namespace {generatedNamespace}.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class SynaptrixAotPipelineBehaviors");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Replaces every open-generic pipeline-behavior registration with the closed ones, so an");
        sb.AppendLine("        /// ahead-of-time compiled host can resolve behaviors whose response type is a value type.");
        sb.AppendLine("        /// Call it after the handler registrations: it removes what they registered open.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddSynaptrixAotPipelineBehaviors(this IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            // The open-generic registrations have to go: leaving them in would make the container");
        sb.AppendLine("            // construct the same closed type at runtime - the very thing that cannot work here - and");
        sb.AppendLine("            // would also run each behavior twice for the requests registered below.");
        sb.AppendLine("            for (int i = services.Count - 1; i >= 0; i--)");
        sb.AppendLine("            {");
        sb.AppendLine("                var descriptor = services[i];");
        sb.AppendLine("                if (descriptor.ServiceType == typeof(global::Synaptrix.IPipelineBehavior<,>)");
        sb.AppendLine("                    || descriptor.ServiceType == typeof(global::Synaptrix.IStreamPipelineBehavior<,>))");
        sb.AppendLine("                {");
        sb.AppendLine("                    services.RemoveAt(i);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();

        foreach (var pair in pairs)
        {
            sb.AppendLine($"            services.AddTransient<{pair}>();");
        }

        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// The cross product, behaviour by behaviour: the container returns behaviors in registration order,
    /// so every request sees them in the same order it would have seen the open-generic ones.
    /// </summary>
    private static IEnumerable<string> Pairs(
        List<string> behaviors,
        List<(string Request, string Response)> requests,
        string behaviorInterfaceName)
    {
        foreach (var behavior in behaviors)
        {
            foreach (var (request, response) in requests)
            {
                yield return $"{behaviorInterfaceName}<{request}, {response}>, {behavior}<{request}, {response}>";
            }
        }
    }

    /// <summary>
    /// The type's name without its type parameter list: the display format spells them out
    /// (<c>Behavior&lt;TRequest, TResponse&gt;</c>), while the emitted code has to substitute its own.
    /// </summary>
    private static string WithoutTypeParameters(INamedTypeSymbol type)
    {
        var name = type.ToDisplayString(FullyQualified);
        var start = name.IndexOf('<');
        return start < 0 ? name : name.Substring(0, start);
    }

    private static List<(string Request, string Response)> ClosedRequests(
        IEnumerable<INamedTypeSymbol> types,
        INamedTypeSymbol? requestInterface)
    {
        if (requestInterface is null)
        {
            return [];
        }

        var requests = new List<(string Request, string Response)>();

        foreach (var type in types)
        {
            // An open-generic request has no single closed form to register, so it keeps needing the
            // runtime path; nothing can be emitted for it here.
            if (type.IsAbstract || type.IsGenericType || type.TypeKind is not (TypeKind.Class or TypeKind.Struct))
            {
                continue;
            }

            foreach (var @interface in type.AllInterfaces)
            {
                if (!SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, requestInterface))
                {
                    continue;
                }

                requests.Add((
                    type.ToDisplayString(FullyQualified),
                    @interface.TypeArguments[0].ToDisplayString(FullyQualified)));
            }
        }

        return [.. requests.Distinct().OrderBy(r => r.Request, System.StringComparer.Ordinal)];
    }

    /// <summary>
    /// A behaviour is registrable here only when its interface slots are its own type parameters, in
    /// order: that is the shape a closed registration can reproduce by substitution.
    /// </summary>
    private static bool IsOpenGenericBehavior(INamedTypeSymbol type, INamedTypeSymbol? behaviorInterface)
    {
        if (behaviorInterface is null || type.IsAbstract || !type.IsGenericType || type.TypeParameters.Length != 2)
        {
            return false;
        }

        foreach (var @interface in type.AllInterfaces)
        {
            if (!SymbolEqualityComparer.Default.Equals(@interface.OriginalDefinition, behaviorInterface))
            {
                continue;
            }

            if (SymbolEqualityComparer.Default.Equals(@interface.TypeArguments[0], type.TypeParameters[0])
                && SymbolEqualityComparer.Default.Equals(@interface.TypeArguments[1], type.TypeParameters[1]))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Every type this compilation can name: its own, plus those of the assemblies it references that
    /// know Synaptrix at all. Walking the framework's assemblies would cost a lot and find nothing.
    /// </summary>
    private static IEnumerable<INamedTypeSymbol> VisibleTypes(Compilation compilation)
    {
        foreach (var type in TypesIn(compilation.Assembly.GlobalNamespace))
        {
            yield return type;
        }

        foreach (var reference in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            if (!ReferencesSynaptrix(reference))
            {
                continue;
            }

            foreach (var type in TypesIn(reference.GlobalNamespace))
            {
                if (type.DeclaredAccessibility == Accessibility.Public)
                {
                    yield return type;
                }
            }
        }
    }

    private static bool ReferencesSynaptrix(IAssemblySymbol assembly)
    {
        if (assembly.Name.StartsWith("Synaptrix", System.StringComparison.Ordinal))
        {
            return true;
        }

        foreach (var module in assembly.Modules)
        {
            foreach (var referenced in module.ReferencedAssemblies)
            {
                if (referenced.Name.StartsWith("Synaptrix", System.StringComparison.Ordinal))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static IEnumerable<INamedTypeSymbol> TypesIn(INamespaceSymbol @namespace)
    {
        foreach (var member in @namespace.GetMembers())
        {
            if (member is INamespaceSymbol nested)
            {
                foreach (var type in TypesIn(nested))
                {
                    yield return type;
                }
            }
            else if (member is INamedTypeSymbol type)
            {
                yield return type;

                foreach (var nestedType in type.GetTypeMembers())
                {
                    yield return nestedType;
                }
            }
        }
    }
}
